[build]
  publish = "."

# Pas de cache sur les données et le JS
[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/main.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Sécurité admin
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
